root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Binary build command
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  # Binary executable path
  bin = "tmp/main"
  # Enable polling to detect file changes in Docker environments
  poll = true
  # Polling interval (if poll is true)
  poll_interval = 500 # ms
  # Watch these extensions
  include_ext = ["go", "tpl", "tmpl", "html", "yaml"," css", "js","jpg"]
  # Ignore these directories
  exclude_dir = ["tmp", "vendor", "testdata"]
  # Delay after each build
  delay = 1000 # ms
  # Stop running old binary when build errors occur
  stop_on_error = true
  # Log file location
  log = "air.log"

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  # Delete tmp directory on exit
  clean_on_exit = true